name: Provision Infra Tools
on: [workflow_dispatch]
jobs:
  Tool_Provision:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Terrafrom Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve